# Generated by Django 5.0.3 on 2024-04-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_articles', '0004_alter_article_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_name',
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
