openapi: 3.0.3
info:
  title: Skills API
  version: 0.0.1
paths:
  /api/articles/:
    get:
      operationId: articles_list
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArticleList'
          description: ''
    post:
      operationId: articles_create
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      tags:
      - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Article'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Article'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
  /api/articles/{slug}/:
    get:
      operationId: articles_retrieve
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
    put:
      operationId: articles_update
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Article'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Article'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
    patch:
      operationId: articles_partial_update
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedArticle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedArticle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedArticle'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
    delete:
      operationId: articles_destroy
      description: |-
        Allows anyone to display published articles and
        to create a new article by logged in User.

        Uses custom permission `IsOwnerOrReadOnly` that allows only
        author of an article to edit it.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/authors/:
    get:
      operationId: authors_list
      description: |-
        Allows anyone to display users and
        to create a new account by anonymous visitors.

        Uses custom permission `IsAnonymousOrNotAllowed` that allows only
        not logged in user to create an account.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAuthorList'
          description: ''
    post:
      operationId: authors_create
      description: |-
        Allows anyone to display users and
        to create a new account by anonymous visitors.

        Uses custom permission `IsAnonymousOrNotAllowed` that allows only
        not logged in user to create an account.
      tags:
      - authors
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Author'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
  /api/authors/{slug}/:
    get:
      operationId: authors_retrieve
      description: |-
        Allows anyone to display users and
        to create a new account by anonymous visitors.

        Uses custom permission `IsAnonymousOrNotAllowed` that allows only
        not logged in user to create an account.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - authors
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/tags/:
    get:
      operationId: tags_list
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - tags
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTagList'
          description: ''
    post:
      operationId: tags_create
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      tags:
      - tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
  /api/tags/{slug}/:
    get:
      operationId: tags_retrieve
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - tags
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    put:
      operationId: tags_update
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    patch:
      operationId: tags_partial_update
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTag'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
    delete:
      operationId: tags_destroy
      description: |-
        Allows anyone to display tags and articles related to them.

        Uses custom permission `IsStaffOrReadOnly` that allows only
        an staff user to manage tags.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - tags
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Article:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        title:
          type: string
          maxLength: 250
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        pub_date:
          type: string
          format: date-time
        content:
          type: string
        author:
          type: string
          format: uri
          readOnly: true
        tags:
          type: array
          items:
            type: string
            format: uri
      required:
      - author
      - content
      - slug
      - tags
      - title
      - url
    Author:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        user_name:
          type: string
          maxLength: 250
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        email:
          type: string
          format: email
          maxLength: 250
        joined:
          type: string
          format: date-time
        password:
          type: string
          writeOnly: true
          maxLength: 128
        articles:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
      required:
      - articles
      - email
      - password
      - slug
      - url
      - user_name
    PaginatedArticleList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Article'
    PaginatedAuthorList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Author'
    PaginatedTagList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    PatchedArticle:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        title:
          type: string
          maxLength: 250
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        pub_date:
          type: string
          format: date-time
        content:
          type: string
        author:
          type: string
          format: uri
          readOnly: true
        tags:
          type: array
          items:
            type: string
            format: uri
    PatchedTag:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        name:
          type: string
          maxLength: 250
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        articles:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
    Tag:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        name:
          type: string
          maxLength: 250
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        articles:
          type: array
          items:
            type: string
            format: uri
          readOnly: true
      required:
      - articles
      - name
      - slug
      - url
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
